name:                ochanomizu-internship
version:             0.1.0.0
github:              "githubuser/ochanomizu-internship"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ochanomizu-internship#readme>

dependencies:
- base >= 4.7 && < 5
- hasktorch
- hasktorch-tools
- cassava
- bytestring
- vector
- nlp-tools
- utf8-string
- containers
- random
- random-shuffle
- text
- binary
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  ochanomizu-internship-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ochanomizu-internship
  session3-linear-regression:
    main:               Session3.Main
    source-dirs:        src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-reports=-N
    dependencies:
    - ochanomizu-internship
  session4:
    main: Session4.PerceptronAndGate
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Session4.PerceptronAndGate
    dependencies:
      - ochanomizu-internship
  session5:
    main: Session5.Main
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Session5.Main
    dependencies:
      - ochanomizu-internship
  session5-admit:
    main: Session5.Admit
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Session5.Admit
    dependencies:
      - ochanomizu-internship
  session5-admit-nll:
    main: Session5.AdmitNLL
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Session5.AdmitNLL
    dependencies:
      - ochanomizu-internship
  session5-titanic-data:
    main: Session5.DataTitanic
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Session5.DataTitanic
    dependencies:
      - ochanomizu-internship
  session5-titanic-train:
    main: Session5.TitanicTrain
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Session5.TitanicTrain
    dependencies:
      - ochanomizu-internship
  session6-word2vec:
    main: Session6.WordToVec
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Session6.WordToVec
    dependencies:
      - ochanomizu-internship
  session6-word2vec-save:
    main: Session6.WordToVecSave
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Session6.WordToVecEmbedSave
    dependencies:
      - ochanomizu-internship
  session6-word2vec-embedtest:
    main: Session6.WordToVecEmbedTest
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Session6.WordToVecEmbedTest
    dependencies:
      - ochanomizu-internship









tests:
  ochanomizu-internship-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ochanomizu-internship
